import smtplib
import os
import yaml
import traceback
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from datetime import datetime
from typing import Optional

import sys
# Add the project root to the python path to allow absolute imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database.models import SessionLocal, Alert

def load_alert_config() -> dict:
    """
    Load alert config from configs/config.yaml.
    Override smtp_user and smtp_password with env vars SMTP_USER and SMTP_PASSWORD
    if they are set (for security — avoid hardcoding credentials).
    Return config dict with keys: threshold_km2, email_enabled, smtp_host,
    smtp_port, smtp_user, smtp_password, sender_name.
    """
    config_path = "configs/config.yaml"
    alert_config = {
        "threshold_km2": 1.0,
        "email_enabled": False,
        "smtp_host": "",
        "smtp_port": 587,
        "smtp_user": "",
        "smtp_password": "",
        "sender_name": "Satellite Change Detector"
    }
    
    if os.path.exists(config_path):
        try:
            with open(config_path, "r") as f:
                config = yaml.safe_load(f) or {}
                if "alerts" in config:
                    alert_config.update(config["alerts"])
        except Exception as e:
            print(f"Warning: Failed to load config.yaml for alerts: {e}")
            
    # Override with env vars
    if os.environ.get("SMTP_USER"):
        alert_config["smtp_user"] = os.environ.get("SMTP_USER")
    if os.environ.get("SMTP_PASSWORD"):
        alert_config["smtp_password"] = os.environ.get("SMTP_PASSWORD")
        
    return alert_config

def compose_alert_email_html(
    recipient_email: str,
    task_id: str,
    changed_area_km2: float,
    tile: str,
    t1_date: str,
    t2_date: str,
    threshold_km2: float,
    result_url: str,
    processing_minutes: float = None
) -> str:
    """
    Return complete HTML string for the alert email body.
    
    Design requirements:
    - Dark professional theme: background #0d1117, card background #161b22
    - Header: satellite emoji + "Change Detection Alert"
    - Summary card with table:
        Row 1: "Tile" | "T43PGQ (Bengaluru, India)"
        Row 2: "Detection Period" | "{t1_date} → {t2_date}"  
        Row 3: "Changed Area" | "{changed_area_km2:.3f} km²" (in red bold)
        Row 4: "Alert Threshold" | "{threshold_km2} km²"
        Row 5: "Detection Time" | current timestamp
    - Red warning badge: "⚠️ THRESHOLD EXCEEDED"
    - Description: "A significant land change of {km²} km² was detected in 
                    satellite tile {tile}, exceeding your configured alert 
                    threshold of {threshold} km². This may indicate construction,
                    deforestation, or other structural changes."
    - "View Results" button: styled anchor tag linking to result_url
      Background: #e74c3c, text: white, padding: 12px 24px, border-radius: 6px
    - Footer: "This alert was generated by Satellite Change Detection System"
               "To stop receiving alerts, remove your email from the application."
    
    Use only inline CSS (email clients strip style tags).
    """
    current_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    processing_row = ""
    if processing_minutes is not None:
        processing_row = f"""
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Processing Time</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #ffffff; text-align: right;">{processing_minutes} minutes on cloud CPU</td>
                    </tr>"""
    html = f"""
    <div style="background-color: #0d1117; color: #c9d1d9; font-family: Arial, sans-serif; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto; background-color: #161b22; border-radius: 8px; overflow: hidden; border: 1px solid #30363d;">
            <div style="padding: 20px; border-bottom: 1px solid #30363d; text-align: center;">
                <h2 style="margin: 0; color: #ffffff;">✅ Satellite Change Detection Complete</h2>
                <div style="margin-top: 10px;">
                    <span style="background-color: #e74c3c; color: white; padding: 4px 8px; border-radius: 4px; font-weight: bold; font-size: 12px;">⚠️ THRESHOLD EXCEEDED</span>
                </div>
            </div>
            <div style="padding: 20px;">
                <p style="line-height: 1.6; font-size: 14px;">
                    A significant land change of <strong>{changed_area_km2:.3f} km²</strong> was detected in 
                    satellite tile <strong>{tile}</strong>, exceeding your configured alert 
                    threshold of <strong>{threshold_km2} km²</strong>. This may indicate construction,
                    deforestation, or other structural changes.
                </p>
                <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px;">
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Job ID</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #ffffff; text-align: right; font-family: monospace; font-size: 12px;">{task_id}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Tile</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #ffffff; text-align: right;">{tile} (Bengaluru, India)</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Detection Period</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #ffffff; text-align: right;">{t1_date} &rarr; {t2_date}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Changed Area</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; text-align: right;"><span style="color: #ff7b72; font-weight: bold;">{changed_area_km2:.3f} km²</span></td>
                    </tr>
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Alert Threshold</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #ffffff; text-align: right;">{threshold_km2} km²</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #8b949e;">Completed At</td>
                        <td style="padding: 8px; border-bottom: 1px solid #30363d; color: #ffffff; text-align: right;">{current_time} UTC</td>
                    </tr>
                    {processing_row}
                </table>
                <div style="text-align: center; margin-top: 30px; margin-bottom: 10px;">
                    <a href="{result_url}" style="background-color: #238636; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; display: inline-block; font-weight: bold;">View Results &rarr;</a>
                </div>
            </div>
            <div style="background-color: #0d1117; padding: 15px; border-top: 1px solid #30363d; text-align: center; font-size: 12px; color: #8b949e;">
                <p style="margin: 5px 0;">This alert was generated by Satellite Change Detection System</p>
                <p style="margin: 5px 0;">To stop receiving alerts, remove your email from the application.</p>
            </div>
        </div>
    </div>
    """
    return html

def send_alert_email(
    recipient_email: str,
    task_id: str,
    changed_area_km2: float,
    tile: str = "T43PGQ",
    t1_date: str = "2021-03-14",
    t2_date: str = "2023-03-14",
    threshold_km2: float = 1.0,
    result_url: str = "",
    processing_minutes: float = None
) -> bool:
    """
    Send HTML alert email via SMTP.
    
    Steps:
    1. Load config via load_alert_config()
    2. If email_enabled is False: log "Email disabled in config" and return False
    3. Compose MIMEMultipart('alternative') message
    4. Set From, To, Subject headers
       Subject: "🛰️ Satellite Change Alert — {changed_area_km2:.2f} km² detected in {tile}"
    5. Attach plain text fallback: "Change detected: {km²} km². View: {url}"
    6. Attach HTML body from compose_alert_email_html()
    7. Connect to smtp_host:smtp_port with SMTP()
    8. Call starttls()
    9. Login with smtp_user and smtp_password
    10. Send message
    11. Quit connection
    12. Return True
    
    Wrap entire send in try/except Exception:
    - If fails: log full error, return False
    - NEVER raise — email failure must never crash the Celery worker
    """
    try:
        config = load_alert_config()
        if not config.get("email_enabled", False):
            print("Email disabled in config")
            return False
            
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"✅ Satellite Change Detection Complete — {changed_area_km2:.2f} km² changed"
        msg['From'] = f"{config.get('sender_name', 'Satellite Change Detector')} <{config.get('smtp_user', '')}>"
        msg['To'] = recipient_email
        
        text_body = (
            f"✅ Detection Complete!\n"
            f"Changed Area: {changed_area_km2:.3f} km²\n"
            f"Period: {t1_date} → {t2_date}\n"
            f"Tile: {tile}\n"
            f"Job ID: {task_id}\n"
            f"Threshold: {threshold_km2} km²\n"
            + (f"Processing Time: {processing_minutes} minutes on cloud CPU\n" if processing_minutes is not None else "")
            + f"View Results: {result_url}"
        )
        html_body = compose_alert_email_html(
            recipient_email=recipient_email,
            task_id=task_id,
            changed_area_km2=changed_area_km2,
            tile=tile,
            t1_date=t1_date,
            t2_date=t2_date,
            threshold_km2=threshold_km2,
            result_url=result_url,
            processing_minutes=processing_minutes
        )
        
        part1 = MIMEText(text_body, 'plain')
        part2 = MIMEText(html_body, 'html')
        
        msg.attach(part1)
        msg.attach(part2)
        
        server = smtplib.SMTP(config.get("smtp_host"), int(config.get("smtp_port", 587)))
        server.starttls()
        server.login(config.get("smtp_user", ""), config.get("smtp_password", ""))
        server.sendmail(config.get("smtp_user", ""), recipient_email, msg.as_string())
        server.quit()
        return True
    except Exception as e:
        print(f"Failed to send alert email to {recipient_email}: {e}")
        traceback.print_exc()
        return False

def trigger_alert(
    result_id: str,
    changed_area_km2: float,
    threshold_km2: float,
    recipient_email: Optional[str] = None,
    task_id: str = "",
    tile: str = "T43PGQ",
    t1_date: str = "",
    t2_date: str = "",
    processing_minutes: float = None
) -> bool:
    """
    Main function called by Celery worker after inference.
    
    1. Check: if changed_area_km2 <= threshold_km2, return False (no alert)
    2. If threshold exceeded:
       a. Format alert log entry with timestamp + all details
       b. Append to outputs/alerts.log (create if not exists)
       c. Print formatted alert to console with ⚠️ emoji
       d. If recipient_email is not None:
          result_url = f"http://localhost:8000/api/v1/results/{task_id}"
          email_sent = send_alert_email(recipient_email, task_id, 
                                        changed_area_km2, tile,
                                        t1_date, t2_date, threshold_km2, result_url)
          Log: "Alert email sent to {email}" or "Alert email failed"
       e. Return True
    """
    if changed_area_km2 <= threshold_km2:
        return False
        
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    message = f"⚠️ <strong>{changed_area_km2:.2f} km²</strong> detected — threshold {threshold_km2} km² exceeded<br>"
    
    print(f"\n⚠️ [{timestamp}] ALERT: Significant change detected! Area: {changed_area_km2:.4f} km² (Exceeds threshold of {threshold_km2:.4f} km²). Result ID: {result_id}\n")
    
    outputs_dir = Path("outputs")
    outputs_dir.mkdir(parents=True, exist_ok=True)
    log_file = outputs_dir / "alerts.log"
    
    with open(log_file, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] ALERT: Significant change detected! Area: {changed_area_km2:.4f} km² (Exceeds threshold of {threshold_km2:.4f} km²). Result ID: {result_id}\n")
        
    if recipient_email:
        result_url = f"http://localhost:8000/api/v1/results/{task_id}"
        email_sent = send_alert_email(
            recipient_email=recipient_email,
            task_id=task_id,
            changed_area_km2=changed_area_km2,
            tile=tile,
            t1_date=t1_date,
            t2_date=t2_date,
            threshold_km2=threshold_km2,
            result_url=result_url,
            processing_minutes=processing_minutes
        )
        if email_sent:
            print(f"Alert email sent to {recipient_email}")
            message += f"<small>Email sent to: {recipient_email} | {datetime.now().strftime('%d %b %Y %H:%M')}</small>"
        else:
            print(f"Alert email failed to send to {recipient_email}")
            message += f"<small>Email failed to send to: {recipient_email} | {datetime.now().strftime('%d %b %Y %H:%M')}</small>"
    else:
        message += f"<small>No email configured | {datetime.now().strftime('%d %b %Y %H:%M')}</small>"
            
    db = SessionLocal()
    try:
        db_alert = Alert(
            result_id=int(result_id),
            message=message
        )
        db.add(db_alert)
        db.commit()
    except Exception as e:
        print(f"Error saving alert to DB: {e}")
        db.rollback()
    finally:
        db.close()
        
    return True
